# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='pic',
            field=models.ImageField(default='/assets/images/default.jpg', upload_to='assets/images'),
        ),
    ]
